version: '3'
services:
  web:
    build: .
    image: zijiezhao/project5:latest
    ports:
      - "3000:3000"  
    environment:
     - MONGO_URI="mongodb://host.docker.internal:27017"
     - MONGO_DBNAME=user
     - SECRET_KEY="mysecretkey"

    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
