version: '3'
services:
  web:
    build: .
    image: zijiezhao/project5:latest
    ports:
      - "3000:3000"  
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
